/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithPriestRouteImport } from './routes/with-priest'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicOfferRouteImport } from './routes/public-offer'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrthodoxCalendarRouteImport } from './routes/orthodox-calendar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsBariRouteImport } from './routes/destinations.bari'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminPilgrimagesIndexRouteImport } from './routes/_admin/admin.pilgrimages.index'
import { Route as AdminAdminDestinationsIndexRouteImport } from './routes/_admin/admin.destinations.index'
import { Route as AdminAdminBlogIndexRouteImport } from './routes/_admin/admin.blog.index'
import { Route as AdminAdminPilgrimagesNewRouteImport } from './routes/_admin/admin.pilgrimages.new'
import { Route as AdminAdminPilgrimagesIdRouteImport } from './routes/_admin/admin.pilgrimages.$id'
import { Route as AdminAdminDestinationsNewRouteImport } from './routes/_admin/admin.destinations.new'
import { Route as AdminAdminDestinationsIdRouteImport } from './routes/_admin/admin.destinations.$id'
import { Route as AdminAdminBlogNewRouteImport } from './routes/_admin/admin.blog.new'
import { Route as AdminAdminBlogIdRouteImport } from './routes/_admin/admin.blog.$id'

const WithPriestRoute = WithPriestRouteImport.update({
  id: '/with-priest',
  path: '/with-priest',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicOfferRoute = PublicOfferRouteImport.update({
  id: '/public-offer',
  path: '/public-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrthodoxCalendarRoute = OrthodoxCalendarRouteImport.update({
  id: '/orthodox-calendar',
  path: '/orthodox-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsBariRoute = DestinationsBariRouteImport.update({
  id: '/destinations/bari',
  path: '/destinations/bari',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPilgrimagesIndexRoute =
  AdminAdminPilgrimagesIndexRouteImport.update({
    id: '/admin/pilgrimages/',
    path: '/admin/pilgrimages/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminDestinationsIndexRoute =
  AdminAdminDestinationsIndexRouteImport.update({
    id: '/admin/destinations/',
    path: '/admin/destinations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminBlogIndexRoute = AdminAdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPilgrimagesNewRoute =
  AdminAdminPilgrimagesNewRouteImport.update({
    id: '/admin/pilgrimages/new',
    path: '/admin/pilgrimages/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPilgrimagesIdRoute = AdminAdminPilgrimagesIdRouteImport.update({
  id: '/admin/pilgrimages/$id',
  path: '/admin/pilgrimages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDestinationsNewRoute =
  AdminAdminDestinationsNewRouteImport.update({
    id: '/admin/destinations/new',
    path: '/admin/destinations/new',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminDestinationsIdRoute =
  AdminAdminDestinationsIdRouteImport.update({
    id: '/admin/destinations/$id',
    path: '/admin/destinations/$id',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminBlogNewRoute = AdminAdminBlogNewRouteImport.update({
  id: '/admin/blog/new',
  path: '/admin/blog/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBlogIdRoute = AdminAdminBlogIdRouteImport.update({
  id: '/admin/blog/$id',
  path: '/admin/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/orthodox-calendar': typeof OrthodoxCalendarRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/with-priest': typeof WithPriestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/bari': typeof DestinationsBariRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/blog/$id': typeof AdminAdminBlogIdRoute
  '/admin/blog/new': typeof AdminAdminBlogNewRoute
  '/admin/destinations/$id': typeof AdminAdminDestinationsIdRoute
  '/admin/destinations/new': typeof AdminAdminDestinationsNewRoute
  '/admin/pilgrimages/$id': typeof AdminAdminPilgrimagesIdRoute
  '/admin/pilgrimages/new': typeof AdminAdminPilgrimagesNewRoute
  '/admin/blog/': typeof AdminAdminBlogIndexRoute
  '/admin/destinations/': typeof AdminAdminDestinationsIndexRoute
  '/admin/pilgrimages/': typeof AdminAdminPilgrimagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/orthodox-calendar': typeof OrthodoxCalendarRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/with-priest': typeof WithPriestRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/destinations/bari': typeof DestinationsBariRoute
  '/destinations': typeof DestinationsIndexRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/blog/$id': typeof AdminAdminBlogIdRoute
  '/admin/blog/new': typeof AdminAdminBlogNewRoute
  '/admin/destinations/$id': typeof AdminAdminDestinationsIdRoute
  '/admin/destinations/new': typeof AdminAdminDestinationsNewRoute
  '/admin/pilgrimages/$id': typeof AdminAdminPilgrimagesIdRoute
  '/admin/pilgrimages/new': typeof AdminAdminPilgrimagesNewRoute
  '/admin/blog': typeof AdminAdminBlogIndexRoute
  '/admin/destinations': typeof AdminAdminDestinationsIndexRoute
  '/admin/pilgrimages': typeof AdminAdminPilgrimagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/calendar': typeof CalendarRoute
  '/catalog': typeof CatalogRoute
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/orthodox-calendar': typeof OrthodoxCalendarRoute
  '/privacy': typeof PrivacyRoute
  '/public-offer': typeof PublicOfferRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/with-priest': typeof WithPriestRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/destinations/bari': typeof DestinationsBariRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/blog/$id': typeof AdminAdminBlogIdRoute
  '/_admin/admin/blog/new': typeof AdminAdminBlogNewRoute
  '/_admin/admin/destinations/$id': typeof AdminAdminDestinationsIdRoute
  '/_admin/admin/destinations/new': typeof AdminAdminDestinationsNewRoute
  '/_admin/admin/pilgrimages/$id': typeof AdminAdminPilgrimagesIdRoute
  '/_admin/admin/pilgrimages/new': typeof AdminAdminPilgrimagesNewRoute
  '/_admin/admin/blog/': typeof AdminAdminBlogIndexRoute
  '/_admin/admin/destinations/': typeof AdminAdminDestinationsIndexRoute
  '/_admin/admin/pilgrimages/': typeof AdminAdminPilgrimagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/calendar'
    | '/catalog'
    | '/contacts'
    | '/login'
    | '/orthodox-calendar'
    | '/privacy'
    | '/public-offer'
    | '/sitemap.xml'
    | '/with-priest'
    | '/blog/$slug'
    | '/destinations/bari'
    | '/destinations/'
    | '/admin/'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/destinations/$id'
    | '/admin/destinations/new'
    | '/admin/pilgrimages/$id'
    | '/admin/pilgrimages/new'
    | '/admin/blog/'
    | '/admin/destinations/'
    | '/admin/pilgrimages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/calendar'
    | '/catalog'
    | '/contacts'
    | '/login'
    | '/orthodox-calendar'
    | '/privacy'
    | '/public-offer'
    | '/sitemap.xml'
    | '/with-priest'
    | '/blog/$slug'
    | '/destinations/bari'
    | '/destinations'
    | '/admin'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/destinations/$id'
    | '/admin/destinations/new'
    | '/admin/pilgrimages/$id'
    | '/admin/pilgrimages/new'
    | '/admin/blog'
    | '/admin/destinations'
    | '/admin/pilgrimages'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/blog'
    | '/calendar'
    | '/catalog'
    | '/contacts'
    | '/login'
    | '/orthodox-calendar'
    | '/privacy'
    | '/public-offer'
    | '/sitemap.xml'
    | '/with-priest'
    | '/blog_/$slug'
    | '/destinations/bari'
    | '/destinations/'
    | '/_admin/admin/'
    | '/_admin/admin/blog/$id'
    | '/_admin/admin/blog/new'
    | '/_admin/admin/destinations/$id'
    | '/_admin/admin/destinations/new'
    | '/_admin/admin/pilgrimages/$id'
    | '/_admin/admin/pilgrimages/new'
    | '/_admin/admin/blog/'
    | '/_admin/admin/destinations/'
    | '/_admin/admin/pilgrimages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CalendarRoute: typeof CalendarRoute
  CatalogRoute: typeof CatalogRoute
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  OrthodoxCalendarRoute: typeof OrthodoxCalendarRoute
  PrivacyRoute: typeof PrivacyRoute
  PublicOfferRoute: typeof PublicOfferRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WithPriestRoute: typeof WithPriestRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DestinationsBariRoute: typeof DestinationsBariRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/with-priest': {
      id: '/with-priest'
      path: '/with-priest'
      fullPath: '/with-priest'
      preLoaderRoute: typeof WithPriestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-offer': {
      id: '/public-offer'
      path: '/public-offer'
      fullPath: '/public-offer'
      preLoaderRoute: typeof PublicOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orthodox-calendar': {
      id: '/orthodox-calendar'
      path: '/orthodox-calendar'
      fullPath: '/orthodox-calendar'
      preLoaderRoute: typeof OrthodoxCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/bari': {
      id: '/destinations/bari'
      path: '/destinations/bari'
      fullPath: '/destinations/bari'
      preLoaderRoute: typeof DestinationsBariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pilgrimages/': {
      id: '/_admin/admin/pilgrimages/'
      path: '/admin/pilgrimages'
      fullPath: '/admin/pilgrimages/'
      preLoaderRoute: typeof AdminAdminPilgrimagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/destinations/': {
      id: '/_admin/admin/destinations/'
      path: '/admin/destinations'
      fullPath: '/admin/destinations/'
      preLoaderRoute: typeof AdminAdminDestinationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/': {
      id: '/_admin/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminAdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pilgrimages/new': {
      id: '/_admin/admin/pilgrimages/new'
      path: '/admin/pilgrimages/new'
      fullPath: '/admin/pilgrimages/new'
      preLoaderRoute: typeof AdminAdminPilgrimagesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pilgrimages/$id': {
      id: '/_admin/admin/pilgrimages/$id'
      path: '/admin/pilgrimages/$id'
      fullPath: '/admin/pilgrimages/$id'
      preLoaderRoute: typeof AdminAdminPilgrimagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/destinations/new': {
      id: '/_admin/admin/destinations/new'
      path: '/admin/destinations/new'
      fullPath: '/admin/destinations/new'
      preLoaderRoute: typeof AdminAdminDestinationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/destinations/$id': {
      id: '/_admin/admin/destinations/$id'
      path: '/admin/destinations/$id'
      fullPath: '/admin/destinations/$id'
      preLoaderRoute: typeof AdminAdminDestinationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/new': {
      id: '/_admin/admin/blog/new'
      path: '/admin/blog/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminAdminBlogNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/blog/$id': {
      id: '/_admin/admin/blog/$id'
      path: '/admin/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminAdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminBlogIdRoute: typeof AdminAdminBlogIdRoute
  AdminAdminBlogNewRoute: typeof AdminAdminBlogNewRoute
  AdminAdminDestinationsIdRoute: typeof AdminAdminDestinationsIdRoute
  AdminAdminDestinationsNewRoute: typeof AdminAdminDestinationsNewRoute
  AdminAdminPilgrimagesIdRoute: typeof AdminAdminPilgrimagesIdRoute
  AdminAdminPilgrimagesNewRoute: typeof AdminAdminPilgrimagesNewRoute
  AdminAdminBlogIndexRoute: typeof AdminAdminBlogIndexRoute
  AdminAdminDestinationsIndexRoute: typeof AdminAdminDestinationsIndexRoute
  AdminAdminPilgrimagesIndexRoute: typeof AdminAdminPilgrimagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminBlogIdRoute: AdminAdminBlogIdRoute,
  AdminAdminBlogNewRoute: AdminAdminBlogNewRoute,
  AdminAdminDestinationsIdRoute: AdminAdminDestinationsIdRoute,
  AdminAdminDestinationsNewRoute: AdminAdminDestinationsNewRoute,
  AdminAdminPilgrimagesIdRoute: AdminAdminPilgrimagesIdRoute,
  AdminAdminPilgrimagesNewRoute: AdminAdminPilgrimagesNewRoute,
  AdminAdminBlogIndexRoute: AdminAdminBlogIndexRoute,
  AdminAdminDestinationsIndexRoute: AdminAdminDestinationsIndexRoute,
  AdminAdminPilgrimagesIndexRoute: AdminAdminPilgrimagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CalendarRoute: CalendarRoute,
  CatalogRoute: CatalogRoute,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  OrthodoxCalendarRoute: OrthodoxCalendarRoute,
  PrivacyRoute: PrivacyRoute,
  PublicOfferRoute: PublicOfferRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WithPriestRoute: WithPriestRoute,
  BlogSlugRoute: BlogSlugRoute,
  DestinationsBariRoute: DestinationsBariRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
